pipeline {
   agent  {
  label 'slavedocker'
  }
   tools {
    jdk 'java'
    maven 'maven'
   }
   stages {
    stage ('checkOut') {
      steps{
        git branch: 'xebia_poc', credentialsId: 'jenkinsuser', url: 'https://github.com/sakshi151990/Java_Jenkins_CI.git'
      }
    }
    stage ('Build') {
      steps{
        echo "Build"
        sh 'mvn clean compile -f Jenkins_CI_java/pom.xml'
      }
    }
    stage ('Test') {
      steps {
        echo "Testing"
        sh 'mvn -Dmaven.test.failure.ignore=true test -f Jenkins_CI_java/pom.xml' 
        }
       post {
        success {
                junit 'Jenkins_CI_java/target/surefire-reports/**/*.xml' 
        }
       }
    }
    stage ('Package') {
      steps {
        echo "Packaging"
        sh 'mvn install -f Jenkins_CI_java/pom.xml' 
        }  
    }    
     stage ('Build Image') {
      steps {
        echo "Build Image"
        sh '''docker --version
             docker build -t unimoni_poc -e WORKSPACE=${WORKSPACE} ${WORKSPACE}/Jenkins_CI_java
             docker images'''
      }
     }  
   }
}
