pipeline {
agent any
   tools {
    maven 'maven'
  }
  stages {
    
  stage ('checkOut') {
    steps{
    
    git branch: 'xebia_poc', credentialsId: 'jenkinsuser', url: 'https://github.com/sakshi151990/Java_Jenkins_CI.git'
    
    }
    
    
}

stage ('Build') {
  steps{
echo "Build"
       sh 'mvn --version'
  }}
stage ('Test') {
  steps{
echo "test"
  }}
}
}
